name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.YOURESTATE }}
        run: |
          git config --global user.email "danishjajja86@gmail.com"
          git config --global user.name "Danish Mustafa"

          git clone https://danishmustafa86:$HF_TOKEN@huggingface.co/spaces/danishmustafa86/YourEstate space

          rsync -av --exclude='.git' ./ space/

          cd space
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes"
          git push